name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.5.0
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: lucianobrum
        password: ${{ secrets.PWD_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        tags: |
          lucianobrum/go_ci:${{github.run_number}}
          lucianobrum/go_ci:latest
