name: Entrega contínua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa-${{ github.run_number }}

    - name: Stop remote containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.REMOTE_USER }}/apigo
          if [ -e "docker-compose.yml" ]; then sudo docker compose down; fi;

    - name: Copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "docker-compose.yml"
        target: "/home/${{ secrets.REMOTE_USER }}/apigo"

    - name: Start remote containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export HOST=${{ secrets.DBHOST }}
          export USER=${{ secrets.DBUSER }}
          export PASSWORD=${{ secrets.DBPASSWORD }}
          export DBNAME=${{ secrets.DBNAME }}
          export DBPORT=${{ secrets.DBPORT }}
          export PORT=8000
          cd /home/${{ secrets.REMOTE_USER }}/apigo
          sudo docker compose up -d > docker-compose-logs.txt 2>&1
          if [ $? -eq 0 ]; then
            echo "Docker Compose command succeeded."
          else
            echo "Docker Compose command failed."
          fi
