name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: postgres
      DBPORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.19', '1.18', '>=1.19']
        os: ['ubuntu-latest', 'ubuntu-20.04']
    steps:
    - uses: actions/checkout@v3.5.0

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d postgres

    - name: Test
      run: go test -v main_test.go 

  docker:
    needs: test
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  # Deprecated - durante o curso, o deploy passou a ser no ECS em vez do EC2, depois voltei para essa versão, ECS é caro :-(
  #Deploy_EC2:
  #  needs: build
  #  uses: ./.github/workflows/EC2.yml
  #  secrets: inherit

  #Deploy_ECS:
  #  needs: docker
  #  uses: ./.github/workflows/ECS.yml
  #  secrets: inherit
