name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      DBPORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.23', '1.24']
        os: ['ubuntu-latest', 'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3.5.0

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build go artifact
      run: docker compose build
      
    - name: Start Database
      run: docker compose up -d postgres

    - name: Check if Postgres is ready
      run: |
        for i in {1..10}; do
          if docker exec $(docker ps -q -f name=postgres) pg_isready -U postgres; then
            echo "Postgres is ready!"
            exit 0
          fi
          echo "Postgres is not ready yet. Waiting..."
          sleep 1
        done
        echo "Postgres did not become ready in time."
        exit 1
        
    - name: Test
      run: go test -v main_test.go 

  build-artifact:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.0

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: programa-${{ github.run_id }}
        path: docker-compose.yml
        
  docker:
    needs: test
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  # Deprecated - durante o curso, o deploy passou a ser no ECS em vez do EC2, depois voltei para essa versão, ECS é caro :-(
  Deploy_EC2:
    needs: docker
    uses: ./.github/workflows/EC2.yml
    secrets: inherit

  #Deploy_ECS:
  #  needs: docker
  #  uses: ./.github/workflows/ECS.yml
  #  secrets: inherit
