# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "aula_1" ]
  pull_request:
    branches: [ "aula_1" ]

jobs:

  install-docker:
    runs-on: macOS-latest
    steps:
      - name: Install docker
        run: |
          brew install docker docker-machine docker-compose
          sudo docker –version

  test:
    needs: install-docker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['>=1.18', '1.18', '1.17']
        os: [ubuntu-latest, ubuntu-18.04, windows-latest, macOS-latest]
    
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build Postgres DB
      run: docker-compose build
      
    - name: Create Postgres DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
